/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Office
 #	author : miyako
 #	2017/10/14
 #
 # --------------------------------------------------------------------------------*/

#import "Office.h"

#define WORD_UTI @"com.microsoft.Word"
#define WORD_NAME @"Microsoft Word"

#define EXCEL_UTI @"com.microsoft.Excel"
#define EXCEL_NAME @"Microsoft Excel"

#define POWERPOINT_UTI @"com.microsoft.PowerPoint"
#define POWERPOINT_NAME @"Microsoft PowerPoint"

// --- Office
void OFFICE_DOCUMENT_TO_PDF(sLONG_PTR *pResult, PackagePtr pParams);
